SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


--
-- STRUCTURE TABLE `USERS`
--

CREATE TABLE PROJECT_1.USERS (
  idUSERS INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUSERS`));
-- --------------------------------------------------------


--
-- STRUCTURE TABLE `TICKETS`
--

CREATE TABLE PROJECT_1.TICKETS (
  idTICKETS INT NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(255) NULL,
  TITLE VARCHAR(45) NULL,
  PRIMARY KEY (`idTICKETS`));
-- --------------------------------------------------------

--
-- DROPING TO TABLE `TICKETS`
--

INSERT INTO PROJECT_1.TICKETS (`DESCRIPTION`, `TITLE`) VALUES ('SSS', 'NNN');
INSERT INTO PROJECT_1.TICKETS (`DESCRIPTION`, `TITLE`) VALUES ('DDD', 'DD');


-- --------------------------------------------------------

--
-- DROPING TO TABLE `USERS`
--

INSERT INTO `PROJECT_1`.`USERS` (`USERNAME`, `PASSWORD`) VALUES ('SASHA', 'QWE');
INSERT INTO `PROJECT_1`.`USERS` (`USERNAME`, `PASSWORD`) VALUES ('KIR', 'QWE');

-- --------------------------------------------------------
